### ISSUE TITLE
傻逼迷你狗

### ISSUE THREAD

**Issue by CoderOrangesoft** [0-0000/MiniExtend#11]
LLLLLLLLL

**Comment by 0-0000** [comment]
警告！你的行为现在涉嫌侵权！可能面临承担民事责任！
你的 Github Issue 涉嫌侵犯他人人身自由权，著作权等权利。
根据《中华人民共和国宪法》以及相关法律，你应承担民事责任，民事责任不是刑事责任，无论年龄均要追责！


请在 2022/12/4 0:00:00 前和谐你的 Issue 标题以及内容（将其设为有积极意义的内容，或者设为空内容，内容不得与宪法和法律相违背），并将其关闭！
如果你未能及时实现该目标，我会取证后在 Github 上举报你发布的侵权内容。
如果你在 2022/2/28 18:00:00 前仍未实现上述目标，那么我将到司法机关提起民事诉讼！


再次提醒，诉讼非常严格！由此为被告人间接带来的负面影响与原告无关！如法院公开审理后被告人的个人信息可能在网络上被他人有意窃取并泄露！


None
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "0-0000/MiniExtend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 中午11:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[0-0000/MiniExtend] 傻逼迷你狗 (Issue #11)





 
LLLLLLLLL
