### ISSUE TITLE
文档优化

### ISSUE THREAD

**Issue by 0-0000** [0-0000/miniExtend#5]
优化 Vuepress 文档，主要内容如下：  
- 将绝对路径修改为相对路径一遍文档在 `0-0000.github.io/miniExtend/` 下也能正常阅读。  
- 修复指向不正确的路径，且为缺失 `id` 属性的标签添加 `id` 属性。  
- 提高 miniExtend Core 的地位。  
- 在 miniExtend Core 中添加 `_LUAG` 和 `loadstring()` 函数的描述。  
- 在 miniExtend CustomUI 中添加 `CustomUI.getRootSize()` 函数的描述。  
- 修正一些可能让人引起疑惑的部分。  
- 统一文档风格，尤其是函数原型。

**Comment by kaikaibenkai** [comment]
#6

**Comment by kaikaibenkai** [comment]
@0-0000 没有Maintenancer权限，无法把此议题分配给我

**Comment by kaikaibenkai** [comment]
[新的仓库](https://kaikaibenkai.github.io/MiniExtend/)
